name: Lint and Type

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm install
      - run: pnpm test:format
      - run: pnpm test:types
      - run: pnpm test:lint
