name: Test Multiple Versions

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: pnpm install --frozen-lockfile
      - run: pnpm build # we don't have any other workflows to test build
      - run: pnpm test:spec

  test_matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        react:
          - 18.0.0
          - 18.1.0
          - 18.2.0
          - 18.3.1
          - 19.0.0-rc.1
          - 19.0.0-rc-1b1283ad-20241203
          - 0.0.0-experimental-1b1283ad-20241203
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: pnpm install --frozen-lockfile
      - name: Test ${{ matrix.react }} ${{ matrix.devtools-skip }}
        run: |
          pnpm add -D react@${{ matrix.react }} react-dom@${{ matrix.react }}
          pnpm test:spec
